# Generated by Django 4.1 on 2023-12-23 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_categorie",
                    models.CharField(max_length=50, verbose_name="nom de la categorie"),
                ),
                (
                    "created_at_categorie",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date creation de la categorie"
                    ),
                ),
                (
                    "date_de_publication_categorie",
                    models.DateField(
                        default="2022-11-10",
                        verbose_name="date de publication de la categorie ",
                    ),
                ),
                (
                    "image_categorie",
                    models.ImageField(
                        upload_to="categories/",
                        verbose_name="image de la categorie du modele",
                    ),
                ),
            ],
            options={"verbose_name": "categorie",},
        ),
        migrations.CreateModel(
            name="Modeles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_modele",
                    models.CharField(max_length=50, verbose_name="nom de l'entreprise"),
                ),
                (
                    "email_entreprise",
                    models.EmailField(
                        max_length=50, verbose_name="email de l'entreprise"
                    ),
                ),
                (
                    "created_at_modele",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date creation du modele"
                    ),
                ),
                (
                    "date_de_publication",
                    models.DateField(
                        default="2022-11-10",
                        verbose_name="date de publication du modele ",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(max_length=50, verbose_name="experience level"),
                ),
                (
                    "short_job_description",
                    models.TextField(verbose_name="courte job description"),
                ),
                ("job_description", models.TextField(verbose_name="job description")),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.categories",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "entreprise",},
        ),
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_partenaire",
                    models.CharField(max_length=20, verbose_name="nom des partenaires"),
                ),
                (
                    "logo_partenaire",
                    models.ImageField(
                        upload_to="partenaire/", verbose_name="logo partenaire"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServicesEntreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "services",
                    models.CharField(
                        max_length=50, verbose_name="les services de l'entreprise"
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.modeles",
                    ),
                ),
            ],
            options={"verbose_name": "service de l'entreprise",},
        ),
        migrations.CreateModel(
            name="MailSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_demande",
                    models.CharField(
                        choices=[
                            ("non-defini", "Non Defini"),
                            ("accepte", "Accepté"),
                            ("refuse", "Refusé"),
                        ],
                        default="non-defini",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'envoie de la demande"
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.modeles",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
